### ISSUE TITLE
Seccion "seleccionar pais" los items deben ser clickeables

### ISSUE THREAD

**Issue by rusosnith** [fundhuesped/donde#1]
no se como hacer los IL clickeables sin que sean boton

**Comment by rusosnith** [comment]
Lo mismo en todas las listas (en los listados previos a los mapas)

**Comment by tinchoforever** [comment]
En realidad, ¿Como es lo que queres hacer? Como se ve?
Es solo mobile eso? o es todo?
Te fijaste en la documentacion de materialize?
